### ISSUE TITLE
KeyError: 'LinkKeys'

### ISSUE THREAD

**Issue by Kent-Narun** [digitalbirdo/BT-LinkkeySync#13]
I'm currently using MacOS Majave 10.14 beta.
Ross-MacBook-Pro:Desktop rossoknarun$ sudo ./BT-Linkkeysync.py
---------------------------------
  BT-Linkkeysync by DigitalBird
---------------------------------
> get Bluetooth Link Keys from macOS and store it to blued.plist
> convert exported list from binary to xml
> parse the converted plist
> Convert the Link Keys and store them to btkeys.reg
Traceback (most recent call last):
  File "./BT-Linkkeysync.py", line 45, in <module>
    print("  Bluetooth 2.0:    "+str(len(pl["LinkKeys"].keys()))+ " Links keys found")
KeyError: 'LinkKeys'

**Comment by Kent-Narun** [comment]
<img width="1440" alt="screen shot 2018-08-02 at 10 08 36 am" src="https://user-images.githubusercontent.com/41314683/43560779-53fc8b6a-963e-11e8-9bc7-bb10bfdb38fd.png">

**Comment by OrangeCat9** [comment]
https://github.com/digitalbirdo/BT-LinkkeySync/blob/adb7985d3008a50fcf25ff60ae1f2d38938adbfe/BT-LinkkeySync.py#L15

set `highSierraLoc = True` please

**Comment by MrTomek** [comment]
@OrangeCat9  Unfortunately, this does not solve the problem

**Comment by MrTomek** [comment]
```
Traceback (most recent call last):
  File "./BT-Linkkeysync.py", line 45, in <module>
    print("  Bluetooth 2.0:    "+str(len(pl["LinkKeys"].keys()))+ " Links keys found")
KeyError: 'LinkKeys'
```
macOS High Sierra 10.13.6
iMac 21.5-inch Mid 2011

**Comment by StefanLobbenmeier** [comment]
I had the same issue and resolved it in my branch. Please check if the fix works for you, and don't forget to comment in the pull request if it succeeded :)

**Comment by MrTomek** [comment]
Thanks, well done

**Comment by digitalbirdo** [comment]
I could not test it as I don't have a working hackintosh at the moment, but the change looks good. Thx @StefanLobbenmeier
