### ISSUE TITLE
please support 10.13

### ISSUE THREAD

**Issue by diepnt90** [digitalbirdo/BT-LinkkeySync#4]
I've ran on 10.13 but the key has nothing in it.
therefore cannot import on windows

**Comment by ekuester** [comment]
I support this request heavily. In 10.13 things seem to have changed: There are a blued.plist and a com.apple.blued.plist each with length of 42 bytes, which is an empty plist file. The file of interest containing the link key is com.apple.bluetoothd.plist . So maybe changing the basis file for converting is enough ...

**Comment by johnkgamble** [comment]
@ekuester, did my fix do it for you? It's still working for me a couple weeks later :).

**Comment by ekuester** [comment]
@johnkgamble, yes the fix extracted the Linkkey as expected, however did not helped me with pairing my Apple Magic Mouse in Fedora Linux. Nevertheless, thanx.
