### ISSUE TITLE
Helpful correction in python script

### ISSUE THREAD

**Issue by ekuester** [digitalbirdo/BT-LinkkeySync#7]
In line 15 of the python script I would propose changing true into True, because otherwise you run into an syntax error if you change False against true. A simple-hearted as me made that experience ...

**Comment by whimzee** [comment]
i also ran into this, thank you a lot! there should really be a heads up in `README.md` about this.

**Comment by digitalbirdo** [comment]
closed with 455134ab5d469534e35be0fb389da7239645a429
